package singleton.twoface

import org.scalacheck.Properties
import shapeless.test.illTyped
import singleton.TestUtils._

class TwoFaceDoubleSpec extends Properties("TwoFace.Double") {
  property("Implicit Creation[]") = {
    val a = implicitly[TwoFace.Double[2.0]]
    a.getValue == 2.0 && a.isLiteral
  }
  property("Safe Creation[]") = {
    val a = TwoFace.Double[2.0]
    a.getValue == 2.0 && a.isLiteral
  }
  property("Safe Creation()") = {
    val a = TwoFace.Double(2.0)
    a.getValue == 2.0 && a.isLiteral
  }
  property("Unsafe Creation()") = {
    val a = TwoFace.Double(us(2.0))
    a.getValue == 2.0 && !a.isLiteral
  }

  property("Safe Double + Safe Char") = verifyTF(TwoFace.Double(2.0) + TwoFace.Char('\u0001'), 3.0)
  property("Safe Double + Unsafe Char") = verifyTF(TwoFace.Double(2.0) + TwoFace.Char(us('\u0001')), us(3.0))
  property("Unsafe Double + Safe Char") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Char('\u0001'), us(3.0))
  property("Unsafe Double + Unsafe Char") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Char(us('\u0001')), us(3.0))
  property("Safe Double + Safe Int") = verifyTF(TwoFace.Double(2.0) + TwoFace.Int(1), 3.0)
  property("Safe Double + Unsafe Int") = verifyTF(TwoFace.Double(2.0) + TwoFace.Int(us(1)), us(3.0))
  property("Unsafe Double + Safe Int") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Int(1), us(3.0))
  property("Unsafe Double + Unsafe Int") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Int(us(1)), us(3.0))
  property("Safe Double + Safe Long") = verifyTF(TwoFace.Double(2.0) + TwoFace.Long(1L), 3.0)
  property("Safe Double + Unsafe Long") = verifyTF(TwoFace.Double(2.0) + TwoFace.Long(us(1L)), us(3.0))
  property("Unsafe Double + Safe Long") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Long(1L), us(3.0))
  property("Unsafe Double + Unsafe Long") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Long(us(1L)), us(3.0))
  property("Safe Double + Safe Float") = verifyTF(TwoFace.Double(2.0) + TwoFace.Float(1.0f), 3.0)
  property("Safe Double + Unsafe Float") = verifyTF(TwoFace.Double(2.0) + TwoFace.Float(us(1.0f)), us(3.0))
  property("Unsafe Double + Safe Float") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Float(1.0f), us(3.0))
  property("Unsafe Double + Unsafe Float") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Float(us(1.0f)), us(3.0))
  property("Safe Double + Safe Double") = verifyTF(TwoFace.Double(2.0) + TwoFace.Double(1.0), 3.0)
  property("Safe Double + Unsafe Double") = verifyTF(TwoFace.Double(2.0) + TwoFace.Double(us(1.0)), us(3.0))
  property("Unsafe Double + Safe Double") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Double(1.0), us(3.0))
  property("Unsafe Double + Unsafe Double") = verifyTF(TwoFace.Double(us(2.0)) + TwoFace.Double(us(1.0)), us(3.0))

  property("Safe Double - Safe Char") = verifyTF(TwoFace.Double(2.0) - TwoFace.Char('\u0001'), 1.0)
  property("Safe Double - Unsafe Char") = verifyTF(TwoFace.Double(2.0) - TwoFace.Char(us('\u0001')), us(1.0))
  property("Unsafe Double - Safe Char") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Char('\u0001'), us(1.0))
  property("Unsafe Double - Unsafe Char") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Char(us('\u0001')), us(1.0))
  property("Safe Double - Safe Int") = verifyTF(TwoFace.Double(2.0) - TwoFace.Int(1), 1.0)
  property("Safe Double - Unsafe Int") = verifyTF(TwoFace.Double(2.0) - TwoFace.Int(us(1)), us(1.0))
  property("Unsafe Double - Safe Int") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Int(1), us(1.0))
  property("Unsafe Double - Unsafe Int") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Int(us(1)), us(1.0))
  property("Safe Double - Safe Long") = verifyTF(TwoFace.Double(2.0) - TwoFace.Long(1L), 1.0)
  property("Safe Double - Unsafe Long") = verifyTF(TwoFace.Double(2.0) - TwoFace.Long(us(1L)), us(1.0))
  property("Unsafe Double - Safe Long") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Long(1L), us(1.0))
  property("Unsafe Double - Unsafe Long") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Long(us(1L)), us(1.0))
  property("Safe Double - Safe Float") = verifyTF(TwoFace.Double(2.0) - TwoFace.Float(1.0f), 1.0)
  property("Safe Double - Unsafe Float") = verifyTF(TwoFace.Double(2.0) - TwoFace.Float(us(1.0f)), us(1.0))
  property("Unsafe Double - Safe Float") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Float(1.0f), us(1.0))
  property("Unsafe Double - Unsafe Float") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Float(us(1.0f)), us(1.0))
  property("Safe Double - Safe Double") = verifyTF(TwoFace.Double(2.0) - TwoFace.Double(1.0), 1.0)
  property("Safe Double - Unsafe Double") = verifyTF(TwoFace.Double(2.0) - TwoFace.Double(us(1.0)), us(1.0))
  property("Unsafe Double - Safe Double") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Double(1.0), us(1.0))
  property("Unsafe Double - Unsafe Double") = verifyTF(TwoFace.Double(us(2.0)) - TwoFace.Double(us(1.0)), us(1.0))

  property("Safe Double * Safe Char") = verifyTF(TwoFace.Double(2.0) * TwoFace.Char('\u0001'), 2.0)
  property("Safe Double * Unsafe Char") = verifyTF(TwoFace.Double(2.0) * TwoFace.Char(us('\u0001')), us(2.0))
  property("Unsafe Double * Safe Char") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Char('\u0001'), us(2.0))
  property("Unsafe Double * Unsafe Char") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Char(us('\u0001')), us(2.0))
  property("Safe Double * Safe Int") = verifyTF(TwoFace.Double(2.0) * TwoFace.Int(1), 2.0)
  property("Safe Double * Unsafe Int") = verifyTF(TwoFace.Double(2.0) * TwoFace.Int(us(1)), us(2.0))
  property("Unsafe Double * Safe Int") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Int(1), us(2.0))
  property("Unsafe Double * Unsafe Int") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Int(us(1)), us(2.0))
  property("Safe Double * Safe Long") = verifyTF(TwoFace.Double(2.0) * TwoFace.Long(1L), 2.0)
  property("Safe Double * Unsafe Long") = verifyTF(TwoFace.Double(2.0) * TwoFace.Long(us(1L)), us(2.0))
  property("Unsafe Double * Safe Long") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Long(1L), us(2.0))
  property("Unsafe Double * Unsafe Long") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Long(us(1L)), us(2.0))
  property("Safe Double * Safe Float") = verifyTF(TwoFace.Double(2.0) * TwoFace.Float(1.0f), 2.0)
  property("Safe Double * Unsafe Float") = verifyTF(TwoFace.Double(2.0) * TwoFace.Float(us(1.0f)), us(2.0))
  property("Unsafe Double * Safe Float") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Float(1.0f), us(2.0))
  property("Unsafe Double * Unsafe Float") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Float(us(1.0f)), us(2.0))
  property("Safe Double * Safe Double") = verifyTF(TwoFace.Double(2.0) * TwoFace.Double(1.0), 2.0)
  property("Safe Double * Unsafe Double") = verifyTF(TwoFace.Double(2.0) * TwoFace.Double(us(1.0)), us(2.0))
  property("Unsafe Double * Safe Double") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Double(1.0), us(2.0))
  property("Unsafe Double * Unsafe Double") = verifyTF(TwoFace.Double(us(2.0)) * TwoFace.Double(us(1.0)), us(2.0))

  property("Safe Double / Safe Char") = verifyTF(TwoFace.Double(6.0) / TwoFace.Char('\u0002'), 3.0)
  property("Safe Double / Unsafe Char") = verifyTF(TwoFace.Double(6.0) / TwoFace.Char(us('\u0002')), us(3.0))
  property("Unsafe Double / Safe Char") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Char('\u0002'), us(3.0))
  property("Unsafe Double / Unsafe Char") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Char(us('\u0002')), us(3.0))
  property("Safe Double / Safe Int") = verifyTF(TwoFace.Double(6.0) / TwoFace.Int(2), 3.0)
  property("Safe Double / Unsafe Int") = verifyTF(TwoFace.Double(6.0) / TwoFace.Int(us(2)), us(3.0))
  property("Unsafe Double / Safe Int") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Int(2), us(3.0))
  property("Unsafe Double / Unsafe Int") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Int(us(2)), us(3.0))
  property("Safe Double / Safe Long") = verifyTF(TwoFace.Double(6.0) / TwoFace.Long(2L), 3.0)
  property("Safe Double / Unsafe Long") = verifyTF(TwoFace.Double(6.0) / TwoFace.Long(us(2L)), us(3.0))
  property("Unsafe Double / Safe Long") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Long(2L), us(3.0))
  property("Unsafe Double / Unsafe Long") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Long(us(2L)), us(3.0))
  property("Safe Double / Safe Float") = verifyTF(TwoFace.Double(6.0) / TwoFace.Float(2.0f), 3.0)
  property("Safe Double / Unsafe Float") = verifyTF(TwoFace.Double(6.0) / TwoFace.Float(us(2.0f)), us(3.0))
  property("Unsafe Double / Safe Float") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Float(2.0f), us(3.0))
  property("Unsafe Double / Unsafe Float") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Float(us(2.0f)), us(3.0))
  property("Safe Double / Safe Double") = verifyTF(TwoFace.Double(6.0) / TwoFace.Double(2.0), 3.0)
  property("Safe Double / Unsafe Double") = verifyTF(TwoFace.Double(6.0) / TwoFace.Double(us(2.0)), us(3.0))
  property("Unsafe Double / Safe Double") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Double(2.0), us(3.0))
  property("Unsafe Double / Unsafe Double") = verifyTF(TwoFace.Double(us(6.0)) / TwoFace.Double(us(2.0)), us(3.0))

  property("Safe Double % Safe Char") = verifyTF(TwoFace.Double(7.0) % TwoFace.Char('\u0004'), 3.0)
  property("Safe Double % Unsafe Char") = verifyTF(TwoFace.Double(7.0) % TwoFace.Char(us('\u0004')), us(3.0))
  property("Unsafe Double % Safe Char") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Char('\u0004'), us(3.0))
  property("Unsafe Double % Unsafe Char") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Char(us('\u0004')), us(3.0))
  property("Safe Double % Safe Int") = verifyTF(TwoFace.Double(7.0) % TwoFace.Int(4), 3.0)
  property("Safe Double % Unsafe Int") = verifyTF(TwoFace.Double(7.0) % TwoFace.Int(us(4)), us(3.0))
  property("Unsafe Double % Safe Int") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Int(4), us(3.0))
  property("Unsafe Double % Unsafe Int") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Int(us(4)), us(3.0))
  property("Safe Double % Safe Long") = verifyTF(TwoFace.Double(7.0) % TwoFace.Long(4L), 3.0)
  property("Safe Double % Unsafe Long") = verifyTF(TwoFace.Double(7.0) % TwoFace.Long(us(4L)), us(3.0))
  property("Unsafe Double % Safe Long") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Long(4L), us(3.0))
  property("Unsafe Double % Unsafe Long") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Long(us(4L)), us(3.0))
  property("Safe Double % Safe Float") = verifyTF(TwoFace.Double(7.0) % TwoFace.Float(4.0f), 3.0)
  property("Safe Double % Unsafe Float") = verifyTF(TwoFace.Double(7.0) % TwoFace.Float(us(4.0f)), us(3.0))
  property("Unsafe Double % Safe Float") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Float(4.0f), us(3.0))
  property("Unsafe Double % Unsafe Float") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Float(us(4.0f)), us(3.0))
  property("Safe Double % Safe Double") = verifyTF(TwoFace.Double(7.0) % TwoFace.Double(4.0), 3.0)
  property("Safe Double % Unsafe Double") = verifyTF(TwoFace.Double(7.0) % TwoFace.Double(us(4.0)), us(3.0))
  property("Unsafe Double % Safe Double") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Double(4.0), us(3.0))
  property("Unsafe Double % Unsafe Double") = verifyTF(TwoFace.Double(us(7.0)) % TwoFace.Double(us(4.0)), us(3.0))

  property("Safe Double < Safe Char") = verifyTF(TwoFace.Double(7.0) < TwoFace.Char('\u0004'), false)
  property("Safe Double < Unsafe Char") = verifyTF(TwoFace.Double(7.0) < TwoFace.Char(us('\u0004')), us(false))
  property("Unsafe Double < Safe Char") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Char('\u0004'), us(false))
  property("Unsafe Double < Unsafe Char") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Char(us('\u0004')), us(false))
  property("Safe Double < Safe Int") = verifyTF(TwoFace.Double(7.0) < TwoFace.Int(4), false)
  property("Safe Double < Unsafe Int") = verifyTF(TwoFace.Double(7.0) < TwoFace.Int(us(4)), us(false))
  property("Unsafe Double < Safe Int") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Int(4), us(false))
  property("Unsafe Double < Unsafe Int") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Int(us(4)), us(false))
  property("Safe Double < Safe Long") = verifyTF(TwoFace.Double(7.0) < TwoFace.Long(4L), false)
  property("Safe Double < Unsafe Long") = verifyTF(TwoFace.Double(7.0) < TwoFace.Long(us(4L)), us(false))
  property("Unsafe Double < Safe Long") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Long(4L), us(false))
  property("Unsafe Double < Unsafe Long") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Long(us(4L)), us(false))
  property("Safe Double < Safe Float") = verifyTF(TwoFace.Double(7.0) < TwoFace.Float(4.0f), false)
  property("Safe Double < Unsafe Float") = verifyTF(TwoFace.Double(7.0) < TwoFace.Float(us(4.0f)), us(false))
  property("Unsafe Double < Safe Float") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Float(4.0f), us(false))
  property("Unsafe Double < Unsafe Float") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Float(us(4.0f)), us(false))
  property("Safe Double < Safe Double") = verifyTF(TwoFace.Double(7.0) < TwoFace.Double(4.0), false)
  property("Safe Double < Unsafe Double") = verifyTF(TwoFace.Double(7.0) < TwoFace.Double(us(4.0)), us(false))
  property("Unsafe Double < Safe Double") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Double(4.0), us(false))
  property("Unsafe Double < Unsafe Double") = verifyTF(TwoFace.Double(us(7.0)) < TwoFace.Double(us(4.0)), us(false))

  property("Safe Double > Safe Char") = verifyTF(TwoFace.Double(7.0) > TwoFace.Char('\u0004'), true)
  property("Safe Double > Unsafe Char") = verifyTF(TwoFace.Double(7.0) > TwoFace.Char(us('\u0004')), us(true))
  property("Unsafe Double > Safe Char") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Char('\u0004'), us(true))
  property("Unsafe Double > Unsafe Char") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Char(us('\u0004')), us(true))
  property("Safe Double > Safe Int") = verifyTF(TwoFace.Double(7.0) > TwoFace.Int(4), true)
  property("Safe Double > Unsafe Int") = verifyTF(TwoFace.Double(7.0) > TwoFace.Int(us(4)), us(true))
  property("Unsafe Double > Safe Int") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Int(4), us(true))
  property("Unsafe Double > Unsafe Int") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Int(us(4)), us(true))
  property("Safe Double > Safe Long") = verifyTF(TwoFace.Double(7.0) > TwoFace.Long(4L), true)
  property("Safe Double > Unsafe Long") = verifyTF(TwoFace.Double(7.0) > TwoFace.Long(us(4L)), us(true))
  property("Unsafe Double > Safe Long") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Long(4L), us(true))
  property("Unsafe Double > Unsafe Long") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Long(us(4L)), us(true))
  property("Safe Double > Safe Float") = verifyTF(TwoFace.Double(7.0) > TwoFace.Float(4.0f), true)
  property("Safe Double > Unsafe Float") = verifyTF(TwoFace.Double(7.0) > TwoFace.Float(us(4.0f)), us(true))
  property("Unsafe Double > Safe Float") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Float(4.0f), us(true))
  property("Unsafe Double > Unsafe Float") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Float(us(4.0f)), us(true))
  property("Safe Double > Safe Double") = verifyTF(TwoFace.Double(7.0) > TwoFace.Double(4.0), true)
  property("Safe Double > Unsafe Double") = verifyTF(TwoFace.Double(7.0) > TwoFace.Double(us(4.0)), us(true))
  property("Unsafe Double > Safe Double") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Double(4.0), us(true))
  property("Unsafe Double > Unsafe Double") = verifyTF(TwoFace.Double(us(7.0)) > TwoFace.Double(us(4.0)), us(true))

  property("Safe Double <= Safe Char") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Char('\u0004'), false)
  property("Safe Double <= Unsafe Char") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Char(us('\u0004')), us(false))
  property("Unsafe Double <= Safe Char") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Char('\u0004'), us(false))
  property("Unsafe Double <= Unsafe Char") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Char(us('\u0004')), us(false))
  property("Safe Double <= Safe Int") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Int(4), false)
  property("Safe Double <= Unsafe Int") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Int(us(4)), us(false))
  property("Unsafe Double <= Safe Int") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Int(4), us(false))
  property("Unsafe Double <= Unsafe Int") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Int(us(4)), us(false))
  property("Safe Double <= Safe Long") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Long(4L), false)
  property("Safe Double <= Unsafe Long") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Long(us(4L)), us(false))
  property("Unsafe Double <= Safe Long") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Long(4L), us(false))
  property("Unsafe Double <= Unsafe Long") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Long(us(4L)), us(false))
  property("Safe Double <= Safe Float") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Float(4.0f), false)
  property("Safe Double <= Unsafe Float") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Float(us(4.0f)), us(false))
  property("Unsafe Double <= Safe Float") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Float(4.0f), us(false))
  property("Unsafe Double <= Unsafe Float") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Float(us(4.0f)), us(false))
  property("Safe Double <= Safe Double") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Double(4.0), false)
  property("Safe Double <= Unsafe Double") = verifyTF(TwoFace.Double(7.0) <= TwoFace.Double(us(4.0)), us(false))
  property("Unsafe Double <= Safe Double") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Double(4.0), us(false))
  property("Unsafe Double <= Unsafe Double") = verifyTF(TwoFace.Double(us(7.0)) <= TwoFace.Double(us(4.0)), us(false))

  property("Safe Double >= Safe Char") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Char('\u0004'), true)
  property("Safe Double >= Unsafe Char") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Char(us('\u0004')), us(true))
  property("Unsafe Double >= Safe Char") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Char('\u0004'), us(true))
  property("Unsafe Double >= Unsafe Char") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Char(us('\u0004')), us(true))
  property("Safe Double >= Safe Int") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Int(4), true)
  property("Safe Double >= Unsafe Int") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Int(us(4)), us(true))
  property("Unsafe Double >= Safe Int") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Int(4), us(true))
  property("Unsafe Double >= Unsafe Int") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Int(us(4)), us(true))
  property("Safe Double >= Safe Long") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Long(4L), true)
  property("Safe Double >= Unsafe Long") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Long(us(4L)), us(true))
  property("Unsafe Double >= Safe Long") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Long(4L), us(true))
  property("Unsafe Double >= Unsafe Long") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Long(us(4L)), us(true))
  property("Safe Double >= Safe Float") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Float(4.0f), true)
  property("Safe Double >= Unsafe Float") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Float(us(4.0f)), us(true))
  property("Unsafe Double >= Safe Float") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Float(4.0f), us(true))
  property("Unsafe Double >= Unsafe Float") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Float(us(4.0f)), us(true))
  property("Safe Double >= Safe Double") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Double(4.0), true)
  property("Safe Double >= Unsafe Double") = verifyTF(TwoFace.Double(7.0) >= TwoFace.Double(us(4.0)), us(true))
  property("Unsafe Double >= Safe Double") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Double(4.0), us(true))
  property("Unsafe Double >= Unsafe Double") = verifyTF(TwoFace.Double(us(7.0)) >= TwoFace.Double(us(4.0)), us(true))

  property("Safe Double == Safe Char") = verifyTF(TwoFace.Double(7.0) == TwoFace.Char('\u0007'), true)
  property("Safe Double == Unsafe Char") = verifyTF(TwoFace.Double(7.0) == TwoFace.Char(us('\u0007')), us(true))
  property("Unsafe Double == Safe Char") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Char('\u0007'), us(true))
  property("Unsafe Double == Unsafe Char") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Char(us('\u0007')), us(true))
  property("Safe Double == Safe Int") = verifyTF(TwoFace.Double(7.0) == TwoFace.Int(7), true)
  property("Safe Double == Unsafe Int") = verifyTF(TwoFace.Double(7.0) == TwoFace.Int(us(7)), us(true))
  property("Unsafe Double == Safe Int") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Int(7), us(true))
  property("Unsafe Double == Unsafe Int") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Int(us(7)), us(true))
  property("Safe Double == Safe Long") = verifyTF(TwoFace.Double(7.0) == TwoFace.Long(7L), true)
  property("Safe Double == Unsafe Long") = verifyTF(TwoFace.Double(7.0) == TwoFace.Long(us(7L)), us(true))
  property("Unsafe Double == Safe Long") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Long(7L), us(true))
  property("Unsafe Double == Unsafe Long") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Long(us(7L)), us(true))
  property("Safe Double == Safe Float") = verifyTF(TwoFace.Double(7.0) == TwoFace.Float(7.0f), true)
  property("Safe Double == Unsafe Float") = verifyTF(TwoFace.Double(7.0) == TwoFace.Float(us(7.0f)), us(true))
  property("Unsafe Double == Safe Float") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Float(7.0f), us(true))
  property("Unsafe Double == Unsafe Float") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Float(us(7.0f)), us(true))
  property("Safe Double == Safe Double") = verifyTF(TwoFace.Double(7.0) == TwoFace.Double(7.0), true)
  property("Safe Double == Unsafe Double") = verifyTF(TwoFace.Double(7.0) == TwoFace.Double(us(7.0)), us(true))
  property("Unsafe Double == Safe Double") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Double(7.0), us(true))
  property("Unsafe Double == Unsafe Double") = verifyTF(TwoFace.Double(us(7.0)) == TwoFace.Double(us(7.0)), us(true))

  property("Safe Double != Safe Char") = verifyTF(TwoFace.Double(7.0) != TwoFace.Char('\u0007'), false)
  property("Safe Double != Unsafe Char") = verifyTF(TwoFace.Double(7.0) != TwoFace.Char(us('\u0007')), us(false))
  property("Unsafe Double != Safe Char") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Char('\u0007'), us(false))
  property("Unsafe Double != Unsafe Char") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Char(us('\u0007')), us(false))
  property("Safe Double != Safe Int") = verifyTF(TwoFace.Double(7.0) != TwoFace.Int(7), false)
  property("Safe Double != Unsafe Int") = verifyTF(TwoFace.Double(7.0) != TwoFace.Int(us(7)), us(false))
  property("Unsafe Double != Safe Int") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Int(7), us(false))
  property("Unsafe Double != Unsafe Int") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Int(us(7)), us(false))
  property("Safe Double != Safe Long") = verifyTF(TwoFace.Double(7.0) != TwoFace.Long(7L), false)
  property("Safe Double != Unsafe Long") = verifyTF(TwoFace.Double(7.0) != TwoFace.Long(us(7L)), us(false))
  property("Unsafe Double != Safe Long") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Long(7L), us(false))
  property("Unsafe Double != Unsafe Long") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Long(us(7L)), us(false))
  property("Safe Double != Safe Float") = verifyTF(TwoFace.Double(7.0) != TwoFace.Float(7.0f), false)
  property("Safe Double != Unsafe Float") = verifyTF(TwoFace.Double(7.0) != TwoFace.Float(us(7.0f)), us(false))
  property("Unsafe Double != Safe Float") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Float(7.0f), us(false))
  property("Unsafe Double != Unsafe Float") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Float(us(7.0f)), us(false))
  property("Safe Double != Safe Double") = verifyTF(TwoFace.Double(7.0) != TwoFace.Double(7.0), false)
  property("Safe Double != Unsafe Double") = verifyTF(TwoFace.Double(7.0) != TwoFace.Double(us(7.0)), us(false))
  property("Unsafe Double != Safe Double") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Double(7.0), us(false))
  property("Unsafe Double != Unsafe Double") = verifyTF(TwoFace.Double(us(7.0)) != TwoFace.Double(us(7.0)), us(false))

  property("Safe Double min Safe Double") = verifyTF(TwoFace.Double(2.0) min TwoFace.Double(1.0), 1.0)
  property("Safe Double min Unsafe Double") = verifyTF(TwoFace.Double(2.0) min TwoFace.Double(us(1.0)), us(1.0))
  property("Unsafe Double min Safe Double") = verifyTF(TwoFace.Double(us(2.0)) min TwoFace.Double(1.0), us(1.0))
  property("Unsafe Double min Unsafe Double") = verifyTF(TwoFace.Double(us(2.0)) min TwoFace.Double(us(1.0)), us(1.0))

  property("Safe Double max Safe Double") = verifyTF(TwoFace.Double(2.0) max TwoFace.Double(1.0), 2.0)
  property("Safe Double max Unsafe Double") = verifyTF(TwoFace.Double(2.0) max TwoFace.Double(us(1.0)), us(2.0))
  property("Unsafe Double max Safe Double") = verifyTF(TwoFace.Double(us(2.0)) max TwoFace.Double(1.0), us(2.0))
  property("Unsafe Double max Unsafe Double") = verifyTF(TwoFace.Double(us(2.0)) max TwoFace.Double(us(1.0)), us(2.0))

  property("Safe Negate") = verifyTF(-TwoFace.Double(-1.0), 1.0)
  property("Unsafe Negate") = verifyTF(-TwoFace.Double(us(1.0)), us(-1.0))

  //  property("Safe toChar") = verifyTF(TwoFace.Double(7.0).toChar, '\u0001')
  //  property("Unsafe toChar") = verifyTF(TwoFace.Double(us(1L)).toChar, us('\u0001'))
  property("Safe toInt") = verifyTF(TwoFace.Double(1.0).toInt, 1)
  property("Unsafe toInt") = verifyTF(TwoFace.Double(us(1.0)).toInt, us(1))
  property("Safe toLong") = verifyTF(TwoFace.Double(1.0).toLong, 1L)
  property("Unsafe toLong") = verifyTF(TwoFace.Double(us(1.0)).toLong, us(1L))
  property("Safe toFloat") = verifyTF(TwoFace.Double(1.0).toFloat, 1.0f)
  property("Unsafe toFloat") = verifyTF(TwoFace.Double(us(1.0)).toFloat, us(1.0f))
  property("Safe toDouble") = verifyTF(TwoFace.Double(1.0).toDouble, 1.0)
  property("Unsafe toDouble") = verifyTF(TwoFace.Double(us(1.0)).toDouble, us(1.0))
  property("Safe toString") = verifyTF(TwoFace.Double(1.0).toString, "1.0")
  property("Unsafe toString") = verifyTF(TwoFace.Double(us(1.0)).toString, us("1.0"))

  property("Implicit Conversions") = wellTyped {
    import singleton.ops._
    val a : TwoFace.Double[3.0] = implicitly[TwoFace.Double[2.0 + 1.0]]
    val b : TwoFace.Double[3.0 + 0.0] = implicitly[TwoFace.Double[2.0 + 1.0]]
    val c : TwoFace.Double[3.0 + 0.0] = implicitly[TwoFace.Double[3.0]]
  }

  property("Wrong Implicit Conversions") = {
    import singleton.ops._
    illTyped("""val a : TwoFace.Double[3.0] = implicitly[TwoFace.Double[2.0 + 2.0]]""")
    illTyped("""val b : TwoFace.Double[3.0 + 0.0] = implicitly[TwoFace.Double[2.0 + 2.0]]""")
    illTyped("""val c : TwoFace.Double[3.0 + 0.0] = implicitly[TwoFace.Double[4.0]]""")
    true
  }
}